name: retro
description: Repository pattern implementation in Dart, with out of the box support for common storage libraries.
version: 1.0.0
repository: https://github.com/tomasweigenast/retro
issue_tracker: https://github.com/tomasweigenast/retro/issues

environment:
  sdk: ^3.1.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
