name: retro
description: Repository pattern implementation in Dart, with out of the box support for common storage libraries.
version: 1.0.7
repository: https://github.com/tomasweigenast/retro
issue_tracker: https://github.com/tomasweigenast/retro/issues

environment:
  sdk: ^3.1.5

dev_dependencies:
  collection: ^1.18.0
  faker: ^2.1.0
  lints: ^3.0.0
  test: ^1.16.0
dependencies:
  hive: ^2.2.3
  meta: ^1.10.0
  retry: ^3.1.2
  universal_html: ^2.2.4
